
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[221] =
    {   0,
        0,    0,    0,    0,    0,    0,   76,   74,   73,   73,
       40,   63,   39,   53,   74,   44,   45,   37,   35,   48,
       36,   47,   38,   60,   60,   50,   46,   33,   49,   31,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   51,   52,   54,   74,   55,
       66,   66,   66,   64,   68,   70,   70,   75,   30,   28,
        0,   41,   42,   61,   69,   72,    0,   60,    0,   60,
        0,   60,   56,   58,   34,   29,   32,   57,   59,    0,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   15,   59,   59,   59,   59,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   27,   67,   66,   65,   66,
       71,   70,   62,    0,   61,    0,   72,   60,   60,    0,
       61,   61,   60,   60,    0,   60,   60,   59,   59,   59,
       23,   59,   59,   59,   59,   59,   59,   59,   18,    3,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,    0,   61,   61,   61,   61,    0,   60,
       60,   59,   20,    2,   59,   59,   24,   59,   16,    5,
       59,   59,   26,   59,   59,   59,   59,   59,   59,   59,
       14,   59,   10,   59,   61,   13,    6,   59,   59,    4,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   17,

       59,   59,   25,   59,   59,    9,   22,   43,   11,   19,
       59,   59,   21,    7,   59,    1,   12,   59,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,    8,    8,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       38,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,    8,   57,    8,   58,   59,   60,   61,

       62,   63,   64,   65,   66,   38,   67,   68,   69,   70,
       71,   72,   38,   73,   74,   75,   76,   77,   78,   51,
       79,   80,   81,   82,   83,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[84] =
    {   0,
        1,    1,    2,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    4,    3,    5,
        5,    5,    5,    3,    3,    3,    3,    3,    5,    5,
        5,    5,    5,    5,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    3,    3,    3,    6,    5,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        3,    3,    3
    } ;

static const flex_int16_t yy_base[232] =
    {   0,
        0,    0,   81,   83,   75,   77,  603,  604,  604,  604,
      575,  604,  604,  591,    0,  604,  604,  604,  585,  604,
      582,   72,   82,   80,   82,  574,  604,   80,  570,   81,
      529,   54,   97,   84,  103,  107,  119,   95,   91,  122,
      123,  137,  145,  115,  152,  604,  604,  604,  498,  604,
      604,  604,  550,  604,  115,  604,  533,    0,  604,  604,
      540,  604,  604,  185,  604,    0,  170,  101,  199,  179,
       94,  205,  604,  604,  604,  604,  604,  604,  491,  488,
      178,  184,  175,  187,  202,  194,  205,  191,  195,  206,
      209,  485,  198,  204,  219,  232,  242,  231,  227,  252,

      254,  255,  243,  256,  257,  604,  604,  604,  604,  520,
      604,  604,  604,  296,  304,  313,    0,  104,  275,  318,
      604,  322,  326,  329,    0,  502,  284,  300,  298,  307,
      459,  308,  306,  312,  327,  329,  320,  338,  458,  444,
      333,  331,  321,  336,  335,  351,  343,  347,  355,  360,
      374,  378,  369,  393,  604,  398,  420,    0,  451,  450,
      354,  389,  408,  407,  387,  388,  372,  375,  322,  314,
      391,  400,  275,  395,  416,  413,  410,  415,  423,  248,
      240,  427,  233,  430,  473,  229,  226,  420,  434,  196,
      440,  424,  451,  467,  443,  469,  473,  471,  477,  193,

      461,  465,  177,  481,  472,  156,  139,  126,  120,  112,
      487,  484,  109,  102,  492,   78,   72,  474,   59,  604,
      554,  560,  564,  566,  572,  578,  584,  587,   92,  589,
      591
    } ;

static const flex_int16_t yy_def[232] =
    {   0,
      220,    1,  221,  221,  222,  222,  220,  220,  220,  220,
      220,  220,  220,  220,  223,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  225,  220,  220,  226,  220,  220,
      220,  220,  220,  220,  220,  227,  220,  220,  220,  220,
      228,  220,  220,  220,  220,  220,  220,  220,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,

      224,  224,  224,  224,  224,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  227,  220,  220,  220,
      220,  220,  220,  220,  229,  230,  231,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  220,  220,  220,  220,  229,  230,  230,
      231,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  220,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,

      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,    0,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220
    } ;

static const flex_int16_t yy_nxt[688] =
    {   0,
        8,    9,   10,    8,    9,   11,   12,    8,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   25,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   31,   31,   37,   31,   31,   38,
       39,   31,   31,   40,   41,   42,   43,   31,   44,   45,
       31,   31,   31,   46,    8,   47,    8,   31,   32,   33,
       34,   35,   36,   31,   31,   37,   31,   38,   39,   31,
       31,   40,   41,   42,   43,   31,   44,   45,   31,   31,
       48,   49,   50,   52,   53,   52,   53,   54,   57,   54,
       57,   64,   64,   64,   64,   65,  158,   67,   81,   67,

       66,   72,   72,   72,   72,   74,   75,   77,   78,   68,
       80,  125,   69,  126,   69,   80,   87,  109,  110,   95,
      118,  119,   70,  118,  118,   82,   81,   94,   80,   58,
       71,   58,   83,   84,   80,   55,   85,   55,   68,   86,
       80,   69,   88,   69,   89,   87,   90,   80,   95,   91,
       70,   80,   92,   80,   82,   98,   94,  104,   80,   80,
       93,   83,   84,   80,   85,   80,   96,   86,   80,   97,
       88,   80,   89,   99,   90,   80,   80,   91,   80,   80,
      102,   92,   80,  100,   98,  104,  101,  105,   93,   64,
       64,   64,   64,   80,   96,   80,  103,   97,  123,  124,

      124,   80,   99,  130,  114,  115,  115,  115,   80,  102,
      128,  100,   80,  120,  101,  120,  105,  116,  121,  122,
      122,  122,   67,  103,   72,   72,   72,   72,  131,  129,
      132,   80,  130,   80,   80,  133,  136,   69,  135,  128,
       80,  134,  137,   80,  140,  141,  116,   80,  138,   80,
       80,   80,   80,  139,   80,  142,  131,  129,   80,  132,
       80,   80,   80,  133,  136,   80,   69,  135,  143,  134,
      137,  145,  140,  141,  144,   80,  138,  146,  198,  147,
      148,  139,   80,   80,  142,   80,  151,   80,   80,   80,
      149,  150,  152,  153,  118,  119,   80,  143,   80,   80,

      145,  125,  144,  160,   80,  146,  147,  198,   80,  148,
       80,   80,   80,   80,  151,  114,  115,  115,  115,  149,
      150,  152,  153,  114,  115,  115,  115,  154,  162,  154,
      163,   80,  155,  156,  156,  156,  116,  121,  122,  122,
      122,  157,  157,  157,  157,  123,  123,  123,  123,  124,
      124,  164,  166,  165,   80,  168,   80,  162,  167,  163,
      170,  169,   80,   80,   80,  116,  171,  172,   80,  174,
       80,  125,  173,  160,  176,  178,   80,   80,   80,  164,
      166,  165,  175,   80,  168,   80,  167,   80,  170,   80,
      169,   80,   80,  179,   80,  171,  172,  174,  177,   80,

      173,  180,  176,   80,  178,  181,  182,   80,  184,  183,
      175,   80,  155,  156,  156,  156,   80,  185,  185,  185,
      185,  179,  189,  192,  188,   80,  177,  186,   80,  180,
       80,   80,  187,  181,   80,  182,  184,  190,  183,  157,
      157,  157,  157,   80,   80,   80,  191,   80,  193,  194,
      189,   80,  192,  188,  195,  186,   80,  196,  199,  197,
      187,  201,  200,   80,   80,  190,   80,  125,  125,   80,
      204,   80,   80,  202,  191,  203,   80,  193,  194,   80,
       80,  205,  195,   80,  207,  196,   80,  199,  197,  201,
       80,  200,  185,  185,  185,  185,   80,  206,  204,   80,

       80,  202,  208,  209,  203,  219,  210,   80,  212,  211,
      205,  213,  207,  214,   80,   80,  217,   80,  215,  125,
      216,   80,  109,   80,  218,   80,  206,   80,   80,   80,
       80,  208,  209,   80,  219,  210,  212,   80,  211,  213,
       80,   80,  214,   80,   80,  217,  215,   80,   80,  216,
      113,  111,  107,  218,   51,   51,   51,   51,   51,   51,
       56,   56,   56,   56,   56,   56,   61,   61,   61,   61,
       79,   79,  108,  108,  108,  108,  108,  108,  112,  106,
      112,  112,  112,  112,  117,   80,  117,  117,  117,  117,
      127,  127,  159,  159,  161,  161,   76,   73,   63,   62,

       60,   59,  220,    7,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220
    } ;

static const flex_int16_t yy_chk[688] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    4,    4,    3,    5,    4,
        6,   22,   22,   22,   22,   23,  229,   24,   32,   25,

       23,   25,   25,   25,   25,   28,   28,   30,   30,   24,
       32,   71,   24,   71,   25,  219,   34,   55,   55,   39,
       68,   68,   24,  118,  118,   33,   32,   38,  217,    5,
       24,    6,   33,   33,  216,    3,   33,    4,   24,   33,
       34,   24,   35,   25,   35,   34,   36,   39,   39,   36,
       24,   38,   37,   33,   33,   41,   38,   44,  214,   35,
       37,   33,   33,   36,   33,  213,   40,   33,  210,   40,
       35,   44,   35,   42,   36,   37,  209,   36,   40,   41,
       43,   37,  208,   42,   41,   44,   42,   45,   37,   67,
       67,   67,   67,   42,   40,  207,   43,   40,   70,   70,

       70,   43,   42,   83,   64,   64,   64,   64,   45,   43,
       81,   42,  206,   69,   42,   69,   45,   64,   69,   69,
       69,   69,   72,   43,   72,   72,   72,   72,   84,   82,
       85,   83,   83,  203,   81,   86,   88,   72,   87,   81,
       82,   86,   89,   84,   93,   94,   64,   88,   90,  200,
       86,   89,  190,   91,   93,   95,   84,   82,   85,   85,
       94,   87,   90,   86,   88,   91,   72,   87,   96,   86,
       89,   97,   93,   94,   96,   95,   90,   98,  180,   99,
      100,   91,  187,   99,   95,  186,  103,   98,   96,  183,
      101,  102,  104,  105,  119,  119,  181,   96,   97,  103,

       97,  127,   96,  127,  180,   98,   99,  180,  100,  100,
      101,  102,  104,  105,  103,  114,  114,  114,  114,  101,
      102,  104,  105,  115,  115,  115,  115,  116,  128,  116,
      129,  173,  116,  116,  116,  116,  115,  120,  120,  120,
      120,  122,  122,  122,  122,  123,  123,  123,  124,  124,
      124,  130,  133,  132,  129,  135,  128,  128,  134,  129,
      137,  136,  133,  130,  132,  115,  138,  141,  134,  143,
      170,  161,  142,  161,  145,  147,  137,  143,  169,  130,
      133,  132,  144,  135,  135,  136,  134,  142,  137,  141,
      136,  145,  144,  148,  138,  138,  141,  143,  146,  147,

      142,  149,  145,  148,  147,  150,  151,  146,  153,  152,
      144,  149,  154,  154,  154,  154,  150,  156,  156,  156,
      156,  148,  168,  174,  166,  153,  146,  162,  167,  149,
      151,  168,  165,  150,  152,  151,  153,  171,  152,  157,
      157,  157,  157,  165,  166,  162,  172,  171,  175,  176,
      168,  174,  174,  166,  177,  162,  172,  178,  182,  179,
      165,  188,  184,  164,  163,  171,  177,  160,  159,  176,
      192,  178,  175,  189,  172,  191,  188,  175,  176,  179,
      192,  193,  177,  182,  195,  178,  184,  182,  179,  188,
      189,  184,  185,  185,  185,  185,  191,  194,  192,  195,

      140,  189,  196,  197,  191,  218,  198,  193,  201,  199,
      193,  202,  195,  204,  139,  131,  212,  201,  205,  126,
      211,  202,  110,  194,  215,  196,  194,  198,  205,  197,
      218,  196,  197,  199,  218,  198,  201,  204,  199,  202,
      212,   92,  204,  211,   80,  212,  205,   79,  215,  211,
       61,   57,   53,  215,  221,  221,  221,  221,  221,  221,
      222,  222,  222,  222,  222,  222,  223,  223,  223,  223,
      224,  224,  225,  225,  225,  225,  225,  225,  226,   49,
      226,  226,  226,  226,  227,   31,  227,  227,  227,  227,
      228,  228,  230,  230,  231,  231,   29,   26,   21,   19,

       14,   11,    7,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[76] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"

  #define  SHOW_TOKENS 0
  #include "syntax.tab.h"
  #include <stdio.h>
  #include <stdlib.h>
  #include <unistd.h>
  #include <string.h>
  #include <math.h>

  char string_buffer[256];
  char comment_buffer[256];
  int errorCounter = 0;

  void print_token(int token_id);
  int str_to_int(char *str);
  float hex_to_float(char *str);
  float str_to_float(char *str);
  void yyerror(const char *err);
#line 719 "lex.yy.c"

#line 721 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENTS 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 35 "lexer.l"

#line 942 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 221 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 604 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "lexer.l"
{ print_token(T_TYPEDEF); return T_TYPEDEF; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "lexer.l"
{ print_token(T_CHAR); return T_CHAR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "lexer.l"
{ print_token(T_INT); return T_INT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "lexer.l"
{ print_token(T_FLOAT); return T_FLOAT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "lexer.l"
{ print_token(T_ENUM); return T_ENUM; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "lexer.l"
{ print_token(T_CLASS); return T_CLASS; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "lexer.l"
{ print_token(T_PRIVATE); return T_PRIVATE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "lexer.l"
{ print_token(T_PROTECTED); return T_PROTECTED; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "lexer.l"
{ print_token(T_PUBLIC); return T_PUBLIC; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "lexer.l"
{ print_token(T_VOID); return T_VOID; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "lexer.l"
{ print_token(T_STATIC); return T_STATIC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "lexer.l"
{ print_token(T_CONTINUE); return T_CONTINUE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "lexer.l"
{ print_token(T_BREAK); return T_BREAK; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "lexer.l"
{ print_token(T_THIS); return T_THIS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "lexer.l"
{ print_token(T_IF); return T_IF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "lexer.l"
{ print_token(T_ELSE); return T_ELSE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "lexer.l"
{ print_token(T_WHILE); return T_WHILE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "lexer.l"
{ print_token(T_FOR); return T_FOR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "lexer.l"
{ print_token(T_SWITCH); return T_SWITCH; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "lexer.l"
{ print_token(T_CASE); return T_CASE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "lexer.l"
{ print_token(T_DEFAULT); return T_DEFAULT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "lexer.l"
{ print_token(T_RETURN); return T_RETURN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "lexer.l"
{ print_token(T_CIN); return T_CIN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "lexer.l"
{ print_token(T_COUT); return T_COUT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "lexer.l"
{ print_token(T_LENGTH); return T_LENGTH; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "lexer.l"
{ print_token(T_MAIN); return T_MAIN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "lexer.l"
{ print_token(T_OROP); return T_OROP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "lexer.l"
{ print_token(T_ANDOP); return T_ANDOP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "lexer.l"
{ print_token(T_EQUOP); return T_EQUOP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 66 "lexer.l"
{ print_token(T_EQUOP); return T_EQUOP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 67 "lexer.l"
{ print_token(T_RELOP); return T_RELOP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 68 "lexer.l"
{ print_token(T_RELOP); return T_RELOP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 69 "lexer.l"
{ print_token(T_RELOP); return T_RELOP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 70 "lexer.l"
{ print_token(T_RELOP); return T_RELOP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "lexer.l"
{ print_token(T_ADDOP); return T_ADDOP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 72 "lexer.l"
{ print_token(T_ADDOP); return T_ADDOP; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "lexer.l"
{ print_token(T_MULOP); return T_MULOP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "lexer.l"
{ print_token(T_MULOP); return T_MULOP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "lexer.l"
{ print_token(T_MULOP); return T_MULOP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "lexer.l"
{ print_token(T_NOTOP); return T_NOTOP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "lexer.l"
{ print_token(T_INCDEC); return T_INCDEC; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "lexer.l"
{ print_token(T_INCDEC); return T_INCDEC; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "lexer.l"
{ print_token(T_SIZEOP); return T_SIZEOP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 81 "lexer.l"
{print_token(T_LPAREN); return T_LPAREN;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 82 "lexer.l"
{print_token(T_RPAREN); return T_RPAREN;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 83 "lexer.l"
{print_token(T_SEMI); return T_SEMI;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 84 "lexer.l"
{print_token(T_DOT); return T_DOT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 85 "lexer.l"
{print_token(T_COMMA); return T_COMMA;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 86 "lexer.l"
{print_token(T_ASSIGN); return T_ASSIGN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 87 "lexer.l"
{print_token(T_COLON); return T_COLON;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 88 "lexer.l"
{print_token(T_LBRACK); return T_LBRACK;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 89 "lexer.l"
{print_token(T_RBRACK); return T_RBRACK;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 90 "lexer.l"
{print_token(T_REFER); return T_REFER;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 91 "lexer.l"
{print_token(T_LBRACE); return T_LBRACE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 92 "lexer.l"
{print_token(T_RBRACE); return T_RBRACE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 93 "lexer.l"
{print_token(T_METH); return T_METH;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 94 "lexer.l"
{print_token(T_INP); return T_INP;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 95 "lexer.l"
{print_token(T_OUT); return T_OUT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 98 "lexer.l"
{ print_token(T_ID); yylval.strval=strdup(yytext); return T_ID; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 99 "lexer.l"
{ print_token(T_ICONST); yylval.intval=str_to_int(yytext); return T_ICONST; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 100 "lexer.l"
{ print_token(T_FCONST); yylval.doubleval=str_to_float(yytext); return T_FCONST; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "lexer.l"
{ print_token(T_CCONST); yylval.charval=yytext[1]; return T_CCONST; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "lexer.l"
{ strcpy(string_buffer,"");    BEGIN(STRING)   ;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 104 "lexer.l"
{ BEGIN(INITIAL);              printf("LINE[%d] STRING TOKEN: %s\n",yylineno,string_buffer);yylval.strval=strdup(string_buffer); return T_STRING;}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 105 "lexer.l"
{ }      
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 106 "lexer.l"
{   
                                if(strlen(yytext) == 2){
                                    if(strcmp(yytext,"\\n") == 0){
                                        strcat(string_buffer,"\n");
                                    }else if(strcmp(yytext,"\\t") == 0){
                                        strcat(string_buffer,"\t");
                                    }else if(strcmp(yytext,"\\b") == 0){
                                        strcat(string_buffer,"\b");
                                    }else if(strcmp(yytext,"\\v") == 0){
                                        strcat(string_buffer,"\v");
                                    }else if(strcmp(yytext,"\\f") == 0){
                                        strcat(string_buffer,"\f");
                                    }else if(strcmp(yytext,"\\r") == 0){
                                        strcat(string_buffer,"\r");
                                    }
                                }else{
                                    strcat(string_buffer,yytext);
                                }                                
                            }
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 125 "lexer.l"
{ yyerror("New line found wihtout \\.")        ;}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 126 "lexer.l"
{ yyerror("End of string without closing it.") ;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 127 "lexer.l"
{ yyerror("\nUNKNOWN CHARACTER.")              ;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 130 "lexer.l"
{ printf("LINE[%d] Comment Found\n",yylineno);  BEGIN(COMMENTS) ;}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 131 "lexer.l"
{ }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 132 "lexer.l"
{ BEGIN(INITIAL);  printf("LINE[%d] Comment Ended \n",yylineno) ;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 133 "lexer.l"
{ printf("LINE[%d] Comment Found\n",yylineno); }
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 134 "lexer.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENTS):
#line 137 "lexer.l"
{ print_token(T_EOF); return T_EOF; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 138 "lexer.l"
{ yyerror("UNKNOWN CHARACTER."); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 139 "lexer.l"
ECHO;
	YY_BREAK
#line 1416 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 221 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 221 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 220);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 139 "lexer.l"




void print_token(int token_id) {
    if(SHOW_TOKENS == 0){
        return;
    }
    if (token_id == T_ICONST) {
        printf("LINE[%d] INTEGER TOKEN '%s'. Base 10: %d token id: %d\n", yylineno, yytext, str_to_int(yytext), token_id);
    } else if (token_id == T_FCONST) {
        printf("LINE[%d] FLOAT TOKEN '%s'. Base 10: %f token id: %d\n", yylineno, yytext, str_to_float(yytext), token_id);
    } else {
        printf("LINE[%d] TOKEN '%s' (%d)\n", yylineno, yytext, token_id);
    }
}

int str_to_int(char *str) {
    if ((strncmp(str, "0x", 2) == 0) || strncmp(str, "0X", 2) == 0) {
        return (int) strtoll(&str[2], NULL, 16);
    } else if ((strncmp(str, "0o", 2) == 0) || strncmp(str, "0O", 2) == 0) {
        return (int) strtoll(&str[2], NULL, 8);
    } else if ((strncmp(str, "0b", 2) == 0) || strncmp(str, "0B", 2) == 0) {
        return (int) strtoll(&str[2], NULL, 2);
    } else if (str[0] == '0' && str[1] == '\0') {
        return 0;
    } else {
        return (int) strtoll(str, NULL, 10);
    }
}
float str_to_float(char *str) {
    if ((strncmp(str, "0x", 2) == 0) || strncmp(str, "0X", 2) == 0) {
        return hex_to_float(str);  
    } else {
        return strtof(str, NULL);  
    }
}

float hex_to_float(char *str) {
    unsigned int intValue = 0;
    sscanf(&str[2], "%x", &intValue);  
    float floatValue = *((float*)&intValue); 
    return floatValue;
}


void yyerror(const char *err) {
    if (errorCounter < 5) {
        fprintf(stderr, "ERROR: %s on line %d\n", err, yylineno);
        errorCounter++;
    }
    yyless(1);
}
